### ISSUE TITLE
demo 中测试使用。多点几次切换数据。就不能滚动了

### ISSUE THREAD

**Issue by zeqinjie** [yangKJ/KJBannerViewDemo#21]
demo 中测试使用，多点几次切换数据。就不能滚动了

**Comment by yangKJ** [comment]
切换之后是空数据显示：
- (void)qiehuanAction:(UISwitch*)sender{
    NSArray *images = @[tu2,tu1,@"IMG_4931",tu1];
    NSMutableArray *arr = [NSMutableArray array];
    for (int i=0; i<images.count; i++) {
        KJBannerModel *model = [[KJBannerModel alloc]init];
        model.customImageUrl = images[i];
        model.customTitle = [NSString stringWithFormat:@"新版数据:%d",i];
        [arr addObject:model];
    }
    if (!sender.on) {
        self.banner2.autoScroll = NO;
        self.banner2.isZoom = YES;
        self.banner2.rollType = KJBannerViewRollDirectionTypeLeftToRight;
        self.banner2.imageDatas = arr;
    }else{
        self.banner2.imageDatas = @[];
    }
}

请仔细看看代码，
