### ISSUE TITLE
说说我的心路历程

### ISSUE THREAD

**Issue by 295060456** [yangKJ/KJBannerViewDemo#26]
您好，作者：
这种功能老生常谈，但比较费脑力，大概的需求也无非集中于：
1、横向？纵向？（您已实现）；
2、一格一格的滑动（好像实现的不够完美，还需要考究）；
3、跑马灯式（横、纵）；
4、跑马灯滚动的时间，节奏、频率、速度等（可以根据定时器时间 + contentOffset 改变值来定，如果定时器时间太疏那么看起来很卡）
5、伪3d效果
...
市面上比较流行的，还在维护的，star比较高的，我对比过有如下：
https://github.com/wwmz/WMZBanner（实现的比较复杂，并且和作者吵了一架）
SDCycleScrollView
...
你的这个相比其他要好一些，但是瑕不掩瑜还是存在一些问题：
1、生命周期错乱，或者说给使用者很多误导；
我们知道代理这个你是仿写苹果的，我们的思维模式肯定也是趋同于TableView那一套的来，那么我如果要实现这个界面的功能：
![image](https://user-images.githubusercontent.com/13795605/108849907-48a38980-7615-11eb-83b8-d177e26d4d9e.png)
不能在- (UIView *)kj_BannerView:(KJBannerView *)banner
           BannerViewCell:(KJBannerViewCell *)bannercell
               ImageDatas:(NSArray *)imageDatas
                    Index:(NSInteger)index；此协议里面拿index，正确的应该是在
- (BOOL)kj_BannerView:(KJBannerView*)banner
         CurrentIndex:(NSInteger)index；里面拿index；
2、控件我写在viewdidLoad里面，但是我要使用协议：
- (BOOL)kj_BannerView:(KJBannerView*)banner
         CurrentIndex:(NSInteger)index；则需要在viewWillAppear以后才可以；
那么直接导致，我在
- (BOOL)kj_BannerView:(KJBannerView*)banner
         CurrentIndex:(NSInteger)index；里面对控件进行操作的时候崩溃到masonry，我不得不：
@property(nonatomic,assign)BOOL viewisAppear;
-(void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:animated];
    self.viewisAppear = YES;
}
才可以。
3、
![image](https://user-images.githubusercontent.com/13795605/108850462-fd3dab00-7615-11eb-85f2-c87d68f6f3b7.png)
这个currentIdx是错值我不能使用
4、我的数据源：
![image](https://user-images.githubusercontent.com/13795605/108850663-3249fd80-7616-11eb-865a-69cf240589f8.png)
但是直接第一次走协议的时候index不对，我不敢用
![image](https://user-images.githubusercontent.com/13795605/108850739-455ccd80-7616-11eb-871d-34bbb7f8364f.png)
我调了很久才正确。
你这个框架就这点美中不足，如果是一般的显示就算了，但是要是要根据index，UI做出相应的调整，找Index和恰当的时机就需要我打断点一个个摸索，源码短期内不可能一个字一个字的看完，所以这里提一点，如果将来有机会重构的时候，可以找准位置。我这边的我demo的源代码如果需要可以找我索取。

**Comment by 295060456** [comment]
对了，调试过程中我还使用了KJPageView的currentIndex发现没啥用。才想出KVO的

**Comment by 295060456** [comment]
因为滚动的时候，没有明确滚动的方向，上下左右？
滚动或者是初始化的时候不断刷新UI造成的调用协议的生命周期：
- (BOOL)kj_BannerView:(KJBannerView*)banner
         CurrentIndex:(NSInteger)index；
👇
- (void)kj_BannerViewDidScroll:(KJBannerView *)banner；
👇
- (UIView *)kj_BannerView:(KJBannerView *)banner
           BannerViewCell:(KJBannerViewCell *)bannercell
               ImageDatas:(NSArray *)imageDatas
                    Index:(NSInteger)index


按道理- (UIView *)kj_BannerView:(KJBannerView *)banner
           BannerViewCell:(KJBannerViewCell *)bannercell
               ImageDatas:(NSArray *)imageDatas
                    Index:(NSInteger)index；应该是终值，直接使用
形成一个误导，真正操作还是必须在：
- (BOOL)kj_BannerView:(KJBannerView*)banner
         CurrentIndex:(NSInteger)index；

**Comment by 295060456** [comment]
然后再来说imageDatas，我们比照Tableview数据源是在独立的，不需要进第三方里面。而你这个地方不写
![image](https://user-images.githubusercontent.com/13795605/108851893-89040700-7617-11eb-8fa6-2d4bdd19f772.png)
是不行的。
数据源就在本类，这么转一圈又回来又是累赘。

**Comment by yangKJ** [comment]
哈哈哈，老哥辛苦了!!!
最近空闲时间在写播放器框架，等我那天空闲了来重构一下吧。
