### ISSUE TITLE
怎么整个轮播图会偏向左侧呢？

### ISSUE THREAD

**Issue by sharehoney** [yangKJ/KJBannerViewDemo#27]
嗨，怎么整个轮播图会偏向左侧呢？这样右侧就有一条空白的间隙了，大概20个点宽。
<img width="337" alt="截屏2021-02-26 下午3 05 28" src="https://user-images.githubusercontent.com/5847579/109267172-188dfd80-7844-11eb-8ed6-1aa29b7520a1.png">

**Comment by benhot** [comment]
一样的问题求解

**Comment by yangKJ** [comment]
可以提供一下Demo，
我回头来看看
