### ISSUE TITLE
3.18 更新到作者最新版后的一些问题

### ISSUE THREAD

**Issue by 295060456** [yangKJ/KJBannerViewDemo#30]
最新版很多方法废弃了。我相当于重新熟悉这个模块：
1、KJBannerView.m 文件里面有2个私有属性：@property (nonatomic,assign) BOOL useCustomCell;@property (nonatomic,assign) BOOL useDataSource;
其实较上个版本的来说，是接口没有对外暴露KJBannerViewCell。
1.1、既然自定义cell，那么我这个cell怎么接入你的模块？
1.2、我想在你的默认KJBannerViewCell上加一个image 是加不了的，因为你注释了协议方法，更改了一些生命周期
![image](https://user-images.githubusercontent.com/13795605/111579969-79787800-87e9-11eb-9846-81a56f8ec3ca.png)
2、如果我不改你源代码的基础上，就需要kvo获取KJBannerView.m 私有属性@property (nonatomic,strong) UICollectionView *collectionView;然后反推cell
3、你喜欢用协议，我也认真找过 了，如果我没看错的话，也是没哟相关cell暴露的。
4、而且我看你的demo，你是比较侧重于网络数据回调这块的，我谈谈我的看法，虽然网络数据是高频需求，但是基础需求是本地数据源，网络这块为代表性的各种异步数据一进来，就调用
/// 设置完数据之后，请刷新
- (void)kj_reloadBannerViewDatas;
- 你这个协议方法进行主线程刷新UI。我明白你的意思。
但是最起码要突出本地数据的重点，我看demo里面很多都是网络数据异步
然后你的废弃方法，我是没用。废弃方法没有完全废弃，建议下个版本全部废弃了，目前好像不用废弃方法都不能进本地数据一样。

**Comment by 295060456** [comment]
算了，我拖出来不用pod管理，等你那边ok了我再pod管理。
其实就一行代码的事情：
![image](https://user-images.githubusercontent.com/13795605/111584910-17237580-87f1-11eb-83ff-60dba1fb556c.png)
我给个建议，但反形参名首字母都小写，你看苹果都是小写的。

**Comment by 295060456** [comment]
![image](https://user-images.githubusercontent.com/13795605/111587606-070d9500-87f5-11eb-9313-8a5bdb8a38be.png)
block 没有弱化self

**Comment by 295060456** [comment]
![image](https://user-images.githubusercontent.com/13795605/111589257-345b4280-87f7-11eb-970e-02c87bfca49a.png)
个人建议，把KJBannerViewFlowLayout这个配置文件暴露到h文件里。这样可以增强定制化效果。不建议一个个属性传进去

**Comment by 295060456** [comment]
老铁，这个是我写的timer封装，你看下有没有问题，提下建议，代码里有没有问题，架构上有没有一些建议。
如果可以，我希望你集成我的这个

**Comment by 295060456** [comment]
我之前给你提过一个问题你没回我https://github.com/yangKJ/KJBannerViewDemo/issues/29
一格一格的滑动，类似抖音那种，是tableView的pageEnable属性。最好用系统的，其他滑动控件没得这个，需要自己写。这个就涉及到架构问题了，如果可以基础架构用tableview实现，但是通过transform来交换xy坐标系，让tableview横屏滚动
动画用系统的，我觉得底层api怎么都比自己写要好。放大这些动画自己写，放大倍数，缩小倍数这些。

**Comment by 295060456** [comment]
这是真正的可以无限滚动的demo：
[scol.zip](https://github.com/yangKJ/KJBannerViewDemo/files/6174780/scol.zip)

**Comment by yangKJ** [comment]
我已单独把网络板块抽离出来，然后部分问题也处理了。
