### ISSUE TITLE
代理方法太少了吧

### ISSUE THREAD

**Issue by peterios2016** [yangKJ/KJBannerViewDemo#6]
你的pageControl是在图片里面的，不符合我的需求，所以我需要获取到每次图片滚动的时候的index，希望能增加图片滚动时的代理回调

**Comment by yangKJ** [comment]
/** 滚动时候回调 是否隐藏自带的PageControl */
- (BOOL)kj_BannerView:(KJBannerView *)banner CurrentIndex:(NSInteger)index;
和
/// block回调
@property (nonatomic,readwrite,copy) void(^kSelectBlock)(KJBannerView *banner,NSInteger idx);
都是图片滚动时相关
