### ISSUE TITLE
使用Masonry约束的时候，pageControl获取不到高度位置就错了

### ISSUE THREAD

**Issue by simaier** [yangKJ/KJBannerViewDemo#9]
使用Masonry约束的时候，pageControl获取不到高度位置就错了

**Comment by yangKJ** [comment]
参考做法：

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    KJBannerView *banner = [[KJBannerView alloc]init];
    banner.backgroundColor = UIColor.greenColor;
    [self.view addSubview:banner];
    [banner mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.mas_offset(100);
        make.left.mas_offset(20);
        make.right.mas_offset(-20);
        make.height.mas_equalTo(200);
    }];
    [banner layoutIfNeeded];
    banner.itemWidth = banner.frame.size.width;
    banner.pageControl.pageType = PageControlStyleRectangle;
    banner.pageControl.dotwidth = 10;
    banner.pageControl.dotheight = 2;
    banner.imageType = KJBannerViewImageTypeMix;
    banner.bannerImageViewContentMode = UIViewContentModeScaleAspectFill;
    
    banner.imageDatas = @[tu2,tu1,gif2,gif2,tu2,gif,tu2,gif2];
}

**Comment by yangKJ** [comment]
版本2.0.6 参考做法：
self.banner2 = [[KJBannerView alloc]init];
self.banner2.autoTime = 2;
self.banner2.isZoom = YES;
self.banner2.itemSpace = -10;
self.banner2.itemWidth = 280;
self.banner2.delegate = self;
self.banner2.dataSource = self;
self.banner2.imageType = KJBannerViewImageTypeMix;
self.banner2.pageControl.pageType = PageControlStyleSizeDot;
[self.backView addSubview:self.banner2];
[self.banner2 mas_makeConstraints:^(MASConstraintMaker *make) {
    make.top.left.right.bottom.mas_equalTo(0);
}];
/// 使用Masonry自动布局，请在设置布局之后调用该方法
[self.banner2 kj_useMasonry];

self.banner2.imageDatas = self.temp;
